Allow CoreDNS version strings to contain sufixes (fix #773)
traefik/mesh pull request #774
Opened 2020-10-30 11:20 UTC by 0rax

## What does this PR do?

This PR fixes an issue where the `traefik-mesh-controller/traefik-mesh-prepare` script would fail if the version of CoreDNS deployed in your environment contains a prefix. This has been seen on AWS EKS, where a build version is present (i.e: `v1.6.6-eksbuild.1`).

As described in the #773 issue, this is due to the way [hashicorp/go-version](github.com/hashicorp/go-version) handles version string when verified using `goversion.NewConstraint(">= 1.3, < 1.8")` as it considers any `-suffix` to be a pre-release version instead of a metadata (expecting a `+suffix` instead). This can be fixed by using the form `version.GreaterThanOrEqual("1.3") && version.LessThan("1.8")`.

Fixes #773

### How to test it

* Deploy an AWS EKS v1.17 environment (which would be deployed with CoreDNS v1.6.6-eksbuild.1)
* Deploy the `traefik-mesh` helm chart using this code, which should now be able to be deployed.

The specific use-case describe in the original issue has also been added as a test case in `pkg/dns/dns_test.go` for future reference.

## Additional Notes

This has been tested on an AWS EKS v1.17-eks.3 cluster with the default CNI removed and replaced by Calico.

2020-10-30 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/traefik/mesh?pullRequest=774) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/traefik/mesh?pullRequest=774) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/traefik/mesh?pullRequest=774) it.</sub>

2020-10-30 13:32 UTC, kevinpollet requested changes
Hello @0rax,

Thanks for your PR and interest in Traefik Mesh!

I've added one minor suggestion.

2020-10-30 16:03 UTC, 0rax commented on pkg/dns/dns.go
> +		c.logger.Debug(`CoreDNS version is not supported, must satisfy ">= %s, < %s", got %q`, versionCoreDNSMin, versionCoreDNSMax, version)
Just updated it :)

2020-11-03 09:08 UTC, kevinpollet approved these changes
LGTM 🚢

2020-11-03 09:10 UTC, merged

2020-11-09 18:31 UTC, carlosescura commented
Is there any information about the release date for this fix?

2020-11-10 09:49 UTC, kevinpollet commented
Hello @carlosescura,

We will do a `bugfix` release in the coming days.

Thanks for your interest in Traefik Mesh!

2020-11-10 10:13 UTC, carlosescura commented
Thanks a lot!! 🥇