Update to go1.17
traefik/mesh pull request #806
Opened 2021-12-28 16:44 UTC by kevinpollet

## What does this PR do?

This PR:

- Updates the Go version to `1.17`
- Updates the Traefik dependency version to `v2.5.6`

2021-12-28 16:54 UTC, ldez requested changes

2021-12-28 16:54 UTC, ldez commented on go.mod
>  go 1.16
```suggestion
go 1.17
```

2021-12-28 16:57 UTC, ldez commented
an update of golangci-lint can be useful also https://github.com/traefik/mesh/blob/d69475264c5d0200647cb626933df330900a6f59/Dockerfile#L24

2021-12-28 17:21 UTC, kevinpollet commented
I will do the golangci-lint update thanks for pointing this!
By the way, I do not understand why the integration tests are not executed?! any ideas?

2021-12-28 17:22 UTC, kevinpollet commented
/sem-approve

2021-12-29 08:25 UTC, tomMoulard commented on README.md
> -[![Travis CI Build Status](https://travis-ci.com/traefik/mesh.svg?branch=master)](https://travis-ci.com/traefik/mesh)
You can maybe add the GitHub action status badge instead ?

2021-12-29 08:35 UTC, tomMoulard commented on docs/content/contributing/building-testing.md
> +- `Go` v1.16+
```suggestion
- `Go` v1.17+
```

2021-12-29 08:38 UTC, tomMoulard commented on docs/content/contributing/building-testing.md
> +- `Go` v1.16+
see https://go.dev/doc/modules/gomod-ref#go

2021-12-29 13:03 UTC, kevinpollet commented
/sem-approve

2021-12-30 13:28 UTC, kevinpollet commented
I opened another PR because the semaphore workflow is triggered.

Superseded by https://github.com/traefik/mesh/pull/809

2021-12-30 13:28 UTC, closed without merging